const types = {
	GET_ALL_COMPANIES_REQUEST: 'GET_ALL_COMPANIES_REQUEST',
	GET_ALL_COMPANIES_SUCCESS: 'GET_ALL_COMPANIES_SUCCESS',
	GET_ALL_COMPANIES_FAILURE: 'GET_ALL_COMPANIES_FAILURE',

	GET_COMPANY_PROFILE_REQUEST: 'GET_COMPANY_PROFILE_REQUEST',
	GET_COMPANY_PROFILE_SUCCESS: 'GET_COMPANY_PROFILE_SUCCESS',
	GET_COMPANY_PROFILE_FAILURE: 'GET_COMPANY_PROFILE_FAILURE',

	GET_COMPANY_FINANCIAL_STATEMENTS: 'GET_COMPANY_FINANCIAL_STATEMENTS',
};

export default types;
