const types = {
	GET_ALL_COMPANIES_REQUEST: 'GET_ALL_COMPANIES_REQUEST',
	GET_ALL_COMPANIES_SUCCESS: 'GET_ALL_COMPANIES_SUCCESS',
	GET_ALL_COMPANIES_FAILURE: 'GET_ALL_COMPANIES_FAILURE',

	GET_COMPANY_PROFILE_REQUEST: 'GET_COMPANY_PROFILE_REQUEST',
	GET_COMPANY_PROFILE_SUCCESS: 'GET_COMPANY_PROFILE_SUCCESS',
	GET_COMPANY_PROFILE_FAILURE: 'GET_COMPANY_PROFILE_FAILURE',

	GET_COMPANY_FINANCIAL_STATEMENTS_REQUEST: 'GET_COMPANY_FINANCIAL_STATEMENTS_REQUEST',
	GET_COMPANY_FINANCIAL_STATEMENTS_SUCCESS: 'GET_COMPANY_FINANCIAL_STATEMENTS_SUCCESS',
	GET_COMPANY_FINANCIAL_STATEMENTS_FAILURE: 'GET_COMPANY_FINANCIAL_STATEMENTS_FAILURE',

	SAVE_SNAPSHOT_REQUEST: 'SAVE_SNAPSHOT_REQUEST',
	SAVE_SNAPSHOT_SUCCESS: 'SAVE_SNAPSHOT_SUCCESS',
	SAVE_SNAPSHOT_FAILURE: 'SAVE_SNAPSHOT_FAILURE',

	GET_SNAPSHOT_REQUEST: 'GET_SNAPSHOT_REQUEST',
	GET_SNAPSHOT_SUCCESS: 'GET_SNAPSHOT_SUCCESS',
	GET_SNAPSHOT_FAILURE: 'GET_SNAPSHOT_FAILURE',
};

export default types;
